name: Build Windows

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build-windows:
    runs-on: windows-2022

    steps:  
    - name: Build Windows
      shell: powershell
      run: dir
