name: Build Windows

env:
  CARB_SETTING_SHOW_REMIX_SUPPORT_POPUP: 0

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build-windows:
    runs-on: windows-2022

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Build Windows
      shell: powershell
      run: |
        dir
        Set-ExecutionPolicy -ExecutionPolicy RemoteSigned -Scope Process
        . .\build.bat --rebuild --release