name: Build Linux

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build-linux:
    runs-on: ubuntu-24.04

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Build Linux
      shell:  'script -q -e -c "bash {0}"'
      run: |
        ls -alh
        ./build.sh --rebuild --release