name: Build Linux

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build-linux:
    runs-on: ubuntu-24.04

    steps:
    - name: Build Linux
      shell: bash
      run: ls -alh
